groups:
- name: express_app_alerts
  rules:
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95% of requests are taking more than 300ms to complete"

  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 1%"

  - alert: LowThroughput
    expr: sum(rate(http_requests_total[5m])) < 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low throughput detected"
      description: "Application is receiving less than 1 request per second"

  - alert: HighCpuUsage
    expr: rate(process_cpu_seconds_total[1m]) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80%"

  - alert: HighMemoryUsage
    expr: (process_resident_memory_bytes / (1024 * 1024 * 1024)) > 1.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 1.5GB"